{% set version = "0.2" %}

package:
  name: wincertstore
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wincertstore/wincertstore-{{ version }}.zip
  sha256: 780bd1557c9185c15d9f4221ea7f905cb20b93f7151ca8ccaed9714dce4b327a

build:
  number: 1004
  skip: true  # [not win]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - wincertstore

about:
  home: https://bitbucket.org/tiran/wincertstore
  license: PSF 2
  license_file: LICENSE
  summary: Python module to extract CA and CRL certs from Windows' cert store (ctypes based).

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - ocefpaf
