{% set version = "0.2.1" %}

{% set pip_version = "20.2.3" %}
{% set setuptools_version = "49.6.0" %}

package:
  name: wincertstore
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/w/wincertstore/wincertstore-{{ version }}.zip
    sha256: ebd681f45f4e156493b4fa54f134b9a171d9c0a8de40ae1a0bc96c3092cb8b12
    folder: wincertstore
  # bootstrap pip and setuptools to avoid circular dependency
  # but without losing metadata
  - url: https://pypi.io/packages/py2.py3/p/pip/pip-{{ pip_version }}-py2.py3-none-any.whl
    sha256: 0f35d63b7245205f4060efe1982f5ea2196aa6e5b26c07669adcf800e2542026
    folder: pip_wheel
  - url: https://pypi.io/packages/py3/s/setuptools/setuptools-{{ setuptools_version }}-py3-none-any.whl
    sha256: 4dd5bb0a0a0cff77b46ca5dd3a84857ee48c83e8223886b556613c724994073f
    folder: setuptools_wheel

build:
  number: 0
  skip: true  # [not win]

requirements:
  host:
    - python
  run:
    - python

test:
  imports:
    - wincertstore

about:
  home: https://pypi.org/project/wincertstore/
  license: PSF-2.0
  license_file: wincertstore/LICENSE
  summary: Deprecated Python module to extract CA and CRL certs from Windows' cert store (ctypes based).

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - ocefpaf
