appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure}
travis:
  secure: {BINSTAR_TOKEN: gaSnbcBsnPhfeyJbQq0fGGTeBZ3eN4tfVAjdu9KCv0fdnNPJk87lIvCfwVrHJFs14Oea2Eb/6GNbkDCQKdhAkA/oxgL/+VHslnMqBQxQwNHsN0jzaVNJ4QhiEXZ9IHvd/4E+tBFgblYCZMF2Exf6Vh5KI6I9auCOsA9kMO5fh7Fn4YIzIk6NjOXfOJ5DXTM+I15zrjooJHZfqHupoiSJ9y48ZX0y+mEiLmlb25IOduFJ7BGl5wbH7klDxhXR1/BUu2xdbZsYbK+BeAix3p6yPrLoEXy6ovu3yNu9I4QTitOH5/rWe5It+gh2BplSjbiUtw6eH/dYFuafOFeFKmFp0/6TWnvy0Q1yu0G5rRyqM+6eDzN7QXVF67WrtaNnKAmrlyer/3TxNlBZzNM9VunNjv6Pamgsr2+qqehzNBl598+4Ii09uAPFgz5EN5RJx5cV+uk3uhtbVagtNOz41NzOkJczXz1KWmPEOT9YR2rpPLBFUfHskNji7PlDI2WWeG7EoHYh6iUMNnIHM4N3ZXP0VyeduZgAsMy/tp9wo44Ud7EyCYByDpdXiDFquIAxTeUZAf7shLpoo+owEHvnehnyb0QqC2A459pgyhulYrfiAlfMIOZDGdH/djw/Sd3Agkw9v8iDOJt7t1nI/N8Ds95GFHIMQkk5AGaMqdZNagpMa7c=}
